#!/usr/bin/env bash
# a modifed version of https://github.com/Russell91/sshrc
#
# LICENSE
#
# Copyright (c) 2014 Russell Stewart
#
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to
# the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
# CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
# TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.


SSHHOME=${SSHHOME:=~}
HUMANISM_BASE=${HUMANISM_BASE:="$SSHHOME"}

#CARRYFILES="humanism.sh humanism.test.sh ap.linux-apt ap.osx-brew ap.freebsd-pkg dbg"
CARRYFILES="."
EXCLUDEFILES="--exclude .git --exclude .gitignore --exclude examples --exclude README.md --exclude LICENSE --exclude .prep"

#
# CHECK LOCAL REQUIREMENTS
#
LOCALERR=0
if [ -f "$HUMANISM_BASE/humanism.sh" ]; then
    if ! command -v tar >/dev/null 2>&1; then
        echo >&2 'sshrc: tar required on localhost'
        LOCALERR=1
    else
        SIZE=$(tar czf - $EXCLUDEFILES -h -C $HUMANISM_BASE $CARRYFILES | wc -c)
        if [ $SIZE -gt 65536 ]; then
            echo >&2 $'sshrc: files must be less than 64kb\ncurrent size: '$SIZE' bytes'
            LOCALERR=1
        fi
    fi
    if command -v xxd >/dev/null 2>&1; then
        pack_local () {
             xxd -p
        }
    elif command -v od >/dev/null 2>&1; then
        pack_local () {
            od -v -t x1 | awk '{$1=""; print}' | sed 's/ //g'
            # -t x1 for byte order
            # -w30 for xxd-r-p compat but -w not support on Unix
        }
    else
        echo >&2 'sshrc: od or xxd required on localhost';
        LOCALERR=1
    fi
else
    echo >&2 "sshrc: no such file $HUMANISM_BASE/humanism.sh"
    LOCALERR=1
fi

#
# PACKUP LOCAL ENV
#
PACKEDHUMANISM=""
PACKEDSSHRC=""
if [ $LOCALERR -eq 0 ]; then
    PACKEDHUMANISM=$(tar czf - $EXCLUDEFILES -h -C $HUMANISM_BASE $CARRYFILES | pack_local)
    PACKEDSSHRC=$(cat "$0" | pack_local)
fi

#
# PREPARE SSH EXEC SCRIPT TO CARRY ENV
#
COPYSCRIPT=$"
CARRY=1
# HUMANISM_BASE wont show until after we login
# so to check if it exists we grep rc files instead
if grep humanism.sh .bashrc >/dev/null 2>&1 || \
   grep humanism.sh .profile >/dev/null 2>&1 || \
   grep humanism.sh /etc/bashrc >/dev/null 2>&1 || \
   grep humanism.sh /etc/profile >/dev/null 2>&1 || \
   grep humanism.sh .zshrc >/dev/null 2>&1 || \
   grep humanism.sh /etc/zshenv >/dev/null 2>&1; then
    echo >&2 'sshrc: humanism found'
    CARRY=0
fi

DESIREDSHELL=\$(command -v $(basename $SHELL) || command -v bash || command -v ash || command -v sh)

if [ \$CARRY -eq 1 ]; then
    # unpack commands on remote/target
    if command -v tar >/dev/null 2>&1; then
        if command -v sed >/dev/null 2>&1; then
            unpack_remote () {
                echo -en \$(echo -n \"\$*\" | tr -d '\n' | sed 's/ //g' | sed 's/../\\\\x&/g')
            }
        elif command -v xxd >/dev/null 2>&1; then
            unpack_remote () {
                echo >&2 'remote unpack with xxd'
                echo -n \"\$*\" | xxd -r -p
            }
        else
            echo >&2 'sshrc: sed or xxd required on remote';
            CARRY=0
        fi
    else
        echo >&2 'sshrc: tar required on remote'
        CARRY=0
    fi
fi

if [ \$CARRY -eq 0 ]; then
    echo >&2 'sshrc: skipping enviornment carry to remote'
    #if [ -e /etc/motd ]; then cat /etc/motd; fi
    \$DESIREDSHELL
else
    #if [ -e /etc/motd ]; then cat /etc/motd; fi
    export SSHHOME=\$(mktemp -d -t .$(whoami).sshrc.XXXX)
    export SSHRCCLEANUP=\$SSHHOME
    trap \"rm -rf \$SSHRCCLEANUP; exit\" 0

    echo 'sshrc: carry sshrc'
    unpack_remote \"$PACKEDSSHRC\" > \$SSHHOME/sshrc
    chmod +x \$SSHHOME/sshrc

    echo 'sshrc: carry humanism.tar.gz'
    unpack_remote \"$PACKEDHUMANISM\" | tar mxz -C \$SSHHOME -f -

    chmod 770 \$SSHHOME
    export SSHHOME=\$SSHHOME

    echo 'sshrc: create sshrc.bashrc'
    PACKEDSSHRCBASHRC=$'"$( cat << 'EOF' | pack_local
    if [ -e /etc/bash.bashrc ]; then source /etc/bash.bashrc; fi
    if [ -e ~/.bashrc ]; then source ~/.bashrc; fi
    export PATH=$PATH:$SSHHOME
    source $SSHHOME/humanism.sh;
    if [ -f $SSHHOME/myrc ]; then
        source "$SSHHOME/myrc"
    fi
EOF
    )"'
    unpack_remote \"\$PACKEDSSHRCBASHRC\" > \$SSHHOME/sshrc.bashrc

    \$DESIREDSHELL --rcfile \$SSHHOME/sshrc.bashrc
fi
"

#
# MAIN
#
if [ $LOCALERR -eq 0 ]; then
    #echo "$COPYSCRIPT" > /tmp/sshrc.debug
    # -t force pseudo tty
    ssh -t $@ "$COPYSCRIPT"
else
    echo >&2 "sshrc: local requirements missing. fall back to normal ssh"
    ssh $@
fi
